DELIMITER $$
CREATE TRIGGER func_delete
BEFORE DELETE ON FUNCIONARIO
FOR EACH ROW
BEGIN
  DELETE FROM Trabalha_em
    WHERE F_CPF = OLD.F_CPF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER setor_delete
BEFORE DELETE ON SETOR
FOR EACH ROW
BEGIN
  DELETE FROM Trabalha_em
    WHERE S_Id = OLD.S_Id;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER remove_produto
AFTER INSERT ON PRODUTO_VENDIDO
FOR EACH ROW
BEGIN
  UPDATE PRODUTOS
     SET Qntd = Qntd - NEW.Qntd
   WHERE P_Id = NEW.P_Id;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER altera_valor_total
AFTER INSERT ON PRODUTO_VENDIDO
FOR EACH ROW
BEGIN
  UPDATE VENDAS
     SET Valor_Total = COALESCE(Valor_Total, 0)
                       + NEW.Qntd
                         * (SELECT Preco FROM PRODUTOS
                              WHERE P_Id = NEW.P_Id)
   WHERE V_Id = NEW.V_Id;
END$$
DELIMITER ;
