use zoo;
DROP TABLE IF EXISTS FUNCIONARIO, TRABALHA_EM, SETOR, HABITAT, LOJA, ANIMAL, VENDAS, CLIENTE, PRODUTOS, PRODUTO_VENDIDO, CONTEM_O;

CREATE TABLE FUNCIONARIO (
	F_CPF VARCHAR(11) PRIMARY KEY,
    F_Telefone VARCHAR(10),
    F_Nome VARCHAR(50)
    );
    
CREATE TABLE TRABALHA_EM (
	F_CPF VARCHAR(11),
    S_Id INT
    );

CREATE TABLE SETOR(
	S_Id INT PRIMARY KEY,
    Nome VARCHAR(50),
    Localizacao VARCHAR(30)
    );

CREATE TABLE HABITAT(
	S_Id INT PRIMARY KEY,
    Temp_media FLOAT,
    Ambiente VARCHAR(30)
);

CREATE TABLE LOJA (
	S_Id INT,
    Tipo VARCHAR(50)
);

CREATE TABLE ANIMAL (
	A_Id INT PRIMARY KEY,
    Altura FLOAT,
    Saude VARCHAR(30),
    Peso FLOAT,
    Especie VARCHAR(50),
    S_Id INT
    );

CREATE TABLE VENDAS (
	V_Id INT PRIMARY KEY,
    Valor_Total FLOAT,
    Data_Compra DATETIME,
    S_Id INT,
    C_CPF VARCHAR(11)
);

CREATE TABLE CLIENTE (
	C_CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(50)
);

CREATE TABLE PRODUTOS (
	P_Id INT PRIMARY KEY,
    Preco FLOAT,
    Qntd INT,
    Nome VARCHAR(50)
    );
    
CREATE TABLE PRODUTO_VENDIDO (
	P_Id INT,
    V_Id INT,
    Qntd INT,
    PRIMARY KEY (P_Id, V_Id)
);

CREATE TABLE CONTEM_O (
	S_Id INT,
    P_Id INT,
    PRIMARY KEY (S_Id, P_Id)
);

ALTER TABLE TRABALHA_EM ADD CONSTRAINT FOREIGN KEY (F_CPF) REFERENCES FUNCIONARIO (F_CPF);
ALTER TABLE TRABALHA_EM ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE HABITAT ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE LOJA ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE ANIMAL ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE VENDAS ADD CONSTRAINT FOREIGN KEY (C_CPF) REFERENCES CLIENTE (C_CPF);
ALTER TABLE VENDAS ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE PRODUTO_VENDIDO ADD CONSTRAINT FOREIGN KEY (V_Id) REFERENCES VENDAS (V_Id);
ALTER TABLE PRODUTO_VENDIDO ADD CONSTRAINT FOREIGN KEY (P_Id) REFERENCES PRODUTOS (P_Id);
ALTER TABLE CONTEM_O ADD CONSTRAINT FOREIGN KEY (S_Id) REFERENCES SETOR (S_Id);
ALTER TABLE CONTEM_O ADD CONSTRAINT FOREIGN KEY (P_Id) REFERENCES PRODUTOS (P_Id);